### ISSUE TITLE
Crash with video of create (In-Game, in inventory)

### ISSUE THREAD

**Issue by MajinRems** [EnigmaticaModpacks/Enigmatica6#5265] opened 2022-11-16 20:57 UTC
### Modpack Version

Enigmatica 6 Expert - E6e - 1.6.1

### Describe your issue.

Hello, sorry for my english.

I found a bug when we are in inventory and we look the demonstration of create about a structure or machine. 

I didn't test in 1.6.2, but i didn't see too in "bugfixes". I can't tell what was the machine or item who crashed the modpack, but if you want to know, i can search with a friend (we tried the bug two both).

Thank's for reading.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

MajinRems#1514

**Comment by NielsPilgaard** [comment] 2022-11-16 21:04
Thanks for the report :)

I'd like to know which video was the issue, and your crash report would also be very helpful.

**Comment by MajinRems** [comment] 2022-11-16 21:14
Okay i found what was the item !

It was "Spout" of create. You have to wait until the end of video, and the last second of video make the modpack close. 
I link you the crash report, but i don't understand nothing at it, so i did'nt open it. 

[crash-2022-11-16_22.12.08-client.txt](https://github.com/EnigmaticaModpacks/Enigmatica6/files/10025769/crash-2022-11-16_22.12.08-client.txt)

**Comment by Kanzaji** [comment] 2022-11-16 21:17
I'm fairly sure this is still this old #4653 issue then😅

**Comment by MajinRems** [comment] 2022-11-16 21:17
Sorry again for my bad english ..

I tried some other videos, but nothing happend. But i tried like 3 or 4 videos, not all of create !

It's not important for me, and does not prevent to play. But i prefer to warn you

**Comment by NielsPilgaard** [comment] 2022-11-17 18:47
Duplicate of #4653

**Closed** 2022-11-17 18:46 UTC
Labels: Duplicate
