### ISSUE TITLE
Trying to bulk craft anvil recipes voids items.

### ISSUE THREAD

**Issue by AchalS-iglu** [EnigmaticaModpacks/Enigmatica6#4989] opened 2022-06-12 10:16 UTC
### Modpack Version

1.3.0

### Describe your issue.

I tried to craft bulk craft 3 time in a bottles but the items got voided without giving any time in a bottle. Then I tried to create them one by one, it worked. Not sure if it is intended or not.

Video - https://youtu.be/Tij4ryEP4WY

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by MuteTiefling** [comment] 2022-06-12 12:28
Ok. Side note here. You can't actually use more than one anyway. There shouldn't be anything you need to bulk craft in anvil crafting recipes.

**Comment by MuteTiefling** [comment] 2022-06-15 00:45
Considering Interactio isn't seeing updates at this point, I don't think we'll see a fix for this. Consider it working as intended.

**Closed** 2022-06-15 00:45 UTC
Labels: Bug, Mod Issue, Status: Won't Fix
