### ISSUE TITLE
Sawmill from Environmental missing bunch of recipes

### ISSUE THREAD

**Issue by Tieso2001** [EnigmaticaModpacks/Enigmatica6#4750] opened 2022-05-02 20:55 UTC
### Modpack Version

1.2.1

### Describe your issue.

The Sawmill from the mod Environmental is missing the recipes for converting the logs/planks to stairs/slabs/etc. Some mods do have these recipes but a large number of common wood types do not (like from Oh The Biomes You'll Go). Mushroom-like logs should also not be forgotten (mods that add stems such as Crimson/Warped Stems).

Each wood type should have their Log, Stripped Log, and Planks be able to be converted into the corresponding Planks, Pressure Plates, (Vertical) Slabs, Fences, Buttons, Ladders, Stairs, Signs, Doors, Trapdoors, and Fence Gates. In a lot of cases, there are only recipes to create Crafting Tables, Sticks, and Bowls. All the other recipes are missing.

I have provided a list with the mods of which the wood types have the correct recipes and which are missing.

### CORRECT:
- Minecraft
- Atmospheric
- Upgrade Aquatic
- Environmental

### MISSING:
- Ars Nouveau
- Oh The Biomes You'll Go
- The Undergarden
- Integrated Dynamics
- BetterEnd Forge
- Project: Vibrant Journeys
- Architect's Palette
- Atum 2
- Tinkers' Construct

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by theboo** [comment] 2022-05-02 21:11
Duplicate of #2847 ... Read the thread there for why it hasn't been done already... I'm sure a PR for this compat would be accepted if someone wants to do it

**Closed** 2022-05-02 21:11 UTC
Labels: Duplicate
