### ISSUE TITLE
[E6E] Create Mechanical Harvesters void Ditchbulbs

### ISSUE THREAD

**Issue by bevilp** [EnigmaticaModpacks/Enigmatica6#4725] opened 2022-04-27 19:17 UTC
### Modpack Version

1.2.1

### Describe your issue.

Mechanical Harvesters seem to void ditchbulbs. They get harvested but never get transferred to attached inventory or to other storage through storage interface.

### Have you modified the modpack?

No

### User Modifications

Added effortless building, easy villagers

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NielsPilgaard** [comment] 2022-04-28 17:27
I believe this is due to how Create determines harvestability, sorta duplicate of #3806

**Closed by NielsPilgaard** 2022-04-28 17:27 UTC
Labels: Bug
