### ISSUE TITLE
Ender Tank recipe cannot be auto crafted with Refined storage

### ISSUE THREAD

**Issue by demethan** [EnigmaticaModpacks/Enigmatica6#4739] opened 2022-04-30 20:47 UTC
### Modpack Version

1.1.2

### Describe your issue.

RS won't find the "surprising substantial satchel" in your inventor to craft the ender tank. I have to go look for it and manually set the crafting grid.  I assume it is because each satchel is bound to a different "Entity"!

![image](https://user-images.githubusercontent.com/5810363/166122048-37568ea0-9149-44a0-b0ae-cb0fae393995.png)
![image](https://user-images.githubusercontent.com/5810363/166122053-837c11db-cb70-423b-b03e-78d98d18a948.png)
![image](https://user-images.githubusercontent.com/5810363/166122057-aff5eb36-5d61-4bb7-b8fb-60ba5997ca0c.png)

I haven't tested in a single player game. 

### Crash Report

None

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by theboo** [comment] 2022-04-30 20:50
duplicate of #4714 , will have to use your noodle for this one! it is fully possible to automate these.. check our wiki for some helpful tips! 
https://wiki.enigmatica.net/enigmatica6/gameplay/how-to.../occultism-automating-rituals

**Closed** 2022-04-30 20:50 UTC
Labels: Duplicate

**Comment by demethan** [comment] 2022-04-30 21:02
I don't mean the occultism ritual.. I mean RS doesn't find the satchel to auto craft the tank.  the job just freeze. Yes, I could use an RFTools crafter.  it's just annoying for nothing.

**Comment by Toonlink264** [comment] 2022-04-30 23:22
just craft the satchel at the same time you craft the tank. you can fully automate this with rs

**Comment by MuteTiefling** [comment] 2022-04-30 23:50
Just like you need an intermediary system for many magic crafts, so to do you need one here, even for the three by three craft. Refined storage simply isn't capable of dealing with this, and that was known when the recipes were created.

You'll have to build your own smart external system.

Thankfully, RS natively supports large crafts now, so you can easily encode at many items into the recipe and hand them all handled externally, only returning the final result that RS can detect to the system.

I don't see a reason to change this. Your meant to have to think a little for automating these cleanly.
