### ISSUE TITLE
RS Large Patterns should probably be removed

### ISSUE THREAD

**Issue by MuteTiefling** [EnigmaticaModpacks/Enigmatica6#5195] opened 2022-09-02 16:37 UTC
### Describe your suggestion

Remove RS Large Patterns

### Why would you like this added/changed?

The functionality has been baked into RS for a while now. Don't think we need to keep this mod.

**Comment by NielsPilgaard** [comment] 2022-09-02 16:50
This might cause issues in existing worlds though, no?

**Comment by MuteTiefling** [comment] 2022-09-02 16:57
If it's in use yeah. They'd lose those patterns.

Might have to wait for a breaking change. Just wanted to put up a reminder as I honestly thought we removed it before Expert was released

**Comment by Quezler** [comment] 2022-09-02 19:10
duplicate of #4747 :3

**Comment by MuteTiefling** [comment] 2022-09-02 19:30
lol, fair

**Closed** 2022-09-02 19:30 UTC
Labels: Duplicate, Suggestion
