### ISSUE TITLE
Industrial Foregoing Dye Mixer produces Pane in the Glass Green Dye

### ISSUE THREAD

**Issue by Sohex** [EnigmaticaModpacks/Enigmatica6#5232] opened 2022-10-15 03:52 UTC
### Modpack Version

1.5.1

### Describe your issue.

The dye mixer from industrial foregoing produces the green dye from pane in the glass which is supposed to be disabled.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NielsPilgaard** [comment] 2022-10-15 13:20
Duplicate of #2746, which was incorrectly closed it seems.

**Closed by NielsPilgaard** 2022-10-15 13:20 UTC
Labels: Bug
