### ISSUE TITLE
Adding fuel to Compression Dynamo causes crash

### ISSUE THREAD

**Issue by fnndyl** [EnigmaticaModpacks/Enigmatica6#5262] opened 2022-11-15 18:11 UTC
### Modpack Version

1.6.0

### Describe your issue.

Adding fuel to the compression dynamo crashes my game. Once the dynamo is running everything is fine, but the initial startup crashes no matter what fuel I try.  Playing on expert mode if that makes a difference.

### Crash Report

https://gist.github.com/fnndyl/afae140b34c4fbeb78abb1b1cb6d207f

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NielsPilgaard** [comment] 2022-11-15 18:20
Duplicate of #5255

**Closed by NielsPilgaard** 2022-11-15 18:21 UTC
Labels: Bug

**Comment by NielsPilgaard** [comment] 2022-11-15 18:26
... I renamed the wrong issue here sorry :P
