### ISSUE TITLE
Suggestion: Add CarryOn mod

### ISSUE THREAD

**Issue by 7sergi9** [EnigmaticaModpacks/Enigmatica6#3985] opened 2022-01-05 22:01 UTC
### URL

https://www.curseforge.com/minecraft/mc-mods/carry-on

### Why would you like the mod added?

Leaving aside that this mod had already been added in E2E, carry On would offer a viable alternative for moving simple items, such as chests at the beginning of the game. It can be argued that "cardboard boxes" already exist, but the reality is that to move the chests that is a tremendously inefficient method as it requires "sawdust" (and machines) which is very difficult to get at the beginning of the game (especially in expert mode) and when placing the chests they are almost always in the wrong positions, becoming very tedious. 

Adding this mod would not "replace" cardboard boxes, as cardboard boxes are more efficient for moving spawners and other items, it would simply simplify something we all want and is often requested in the modpack discord (moving chests easily at the beginning of the game).

**Comment by theboo** [comment] 2022-01-05 22:06
Duplicate of: https://github.com/EnigmaticaModpacks/Enigmatica6/issues/2175

**Closed by theboo** 2022-01-05 22:06 UTC
Labels: Suggestion
