### ISSUE TITLE
Tetra crafting table does not allow usage of brass ingots

### ISSUE THREAD

**Issue by jsczesny587** [EnigmaticaModpacks/Enigmatica6#4983] opened 2022-06-11 02:19 UTC
### Modpack Version

1.2.1

### Describe your issue.

Tetra does not allow usage of brass ingots to modify any tools. When trying to apply brass ingots to a tetra tool, the 'Craft' button is greyed out, and when mousing over it it says 'The provided material cannot be used by this schematic.' I suspect this is a bug because, when using the Holosphere to view possible materials to use, brass shows up, but the picture is of the create version of brass rather than the one used by this modpack.
![image](https://user-images.githubusercontent.com/55038161/173168956-71e57156-5007-408a-82af-84397cc8393e.png)
![image](https://user-images.githubusercontent.com/55038161/173168959-3ddd1156-50ac-4732-b55b-c04607484c2e.png)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NielsPilgaard** [comment] 2022-06-11 05:55
Duplicate of #2645 - I'll try to fix it now :)

**Closed by NielsPilgaard** 2022-06-11 05:55 UTC
Labels: Bug
