### ISSUE TITLE
Sawmill missing recipes for BYG logs

### ISSUE THREAD

**Issue by IllegalCharacter** [EnigmaticaModpacks/Enigmatica6#4474] opened 2022-03-22 18:22 UTC
### Describe your suggestion

https://i.imgur.com/HXr7ZOH.png

https://i.imgur.com/Mtmaks2.png

Using vanilla logs, you can make fences, signs, gates etc. with the sawmill. I think the BYG logs should do this as well.  You can't even cut it into planks, just a crafting table, sticks, or a bowl for some reason.

### Why would you like this added/changed?

Would be convenient for making fences and such for decorating

**Comment by NillerMedDild** [comment] 2022-03-22 20:00
Duplicate of #2847 I'm afraid

**Closed by NillerMedDild** 2022-03-22 20:00 UTC
Labels: Suggestion

**Comment by IllegalCharacter** [comment] 2022-03-23 00:57
Sorry, I didn't search for closed issues, I didn't think there would be a reason this would be reported and and refused.

I can agree with not adding it because the functionality exists elsewhere, However, which modded sawmills have this feature? I'm using the one from Environmental, which doesn't include the feature? Maybe I'm overlooking it.

**Comment by NillerMedDild** [comment] 2022-03-23 17:54
The closing comment is this:

>We won't implement this after all because of time constraints :(

It's a good idea, but it also takes a ton of time to implement and get right.

**Comment by IllegalCharacter** [comment] 2022-03-23 18:25
I understand that, I was referring to the earlier comment in that thread

> We already have this through the modded Sawmills, I think that's good enough :)

If it's a available through other methods, I don't see them.

**Comment by NillerMedDild** [comment] 2022-03-24 17:11
The feature you're requesting is not available through other methods, other than regular crafting ofc.
