### ISSUE TITLE
Ars sword and Bow not crafting

### ISSUE THREAD

**Issue by MuchosSassyLass** [EnigmaticaModpacks/Enigmatica6#3833] opened 2021-12-02 19:32 UTC
### Modpack Version

0.5.21

### Describe your issue.

Hello, I tried to make an Ars nouveau sword and it came up "recipe not found". same issue when i tried to make a bow. I made a bow in a previous version with the same setup with no issues. It still lets me make a wand, so I think just the sword and bow aren't working. Another user had the same issue, same version, also singleplayer. 
![image_2021-12-02_153146](https://user-images.githubusercontent.com/95441391/144490221-ea810957-850c-4213-9118-a2c0989be7e0.png)

(there is a second gold block, it just bobbed down as i took the screenshot)

Thanks!

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment] 2021-12-02 21:05
Thanks for the report - Are you supplying it with source? :)

**Comment by MuchosSassyLass** [comment] 2021-12-02 21:33
hmm I have a source jar and glyph press nearby, it didn't affect the wand crafting though. does the sword require source to craft? or is it conflicting maybe?

**Comment by theboo** [comment] 2021-12-02 21:52
Nah, something else must be going on.. those recipes don't need source.. moto is looking in to it

**Comment by MuteTiefling** [comment] 2021-12-02 21:56
moto's instance blew up lol

**Comment by MuteTiefling** [comment] 2021-12-03 10:57
Ok, it's not working in e6, but does work in an instance with default Ars, so something we're doing is confusing it.

**Comment by Padrinony** [comment] 2021-12-17 05:43
I updated to 1.24.8 I believe cause of the same issue in Enigmatic 6 1.16.5 and still says "No Recipe Found"....

**Comment by NillerMedDild** [comment] 2021-12-17 06:46
This fix was on our side and has not yet been released :) it'll be in the next modpack update.

**Comment by chrispiciullo** [comment] 2022-01-09 18:27
I know this is marked as closed and the fix does work for the Sword and Bow in the beta version on CurseForge, however the shield is also unable to be crafted.. It gives the "No Recipe Found" error. I didn't know if I should add it to this issue since it's technically the same problem or if a new one should be created. If you like, I can open a new issue for this. Thanks!

**Comment by NillerMedDild** [comment] 2022-01-09 18:40
> I didn't know if I should add it to this issue (since it's a similar issue to the sword and bow), or if a new one should be created. If you like, I can open a new issue for this. Thanks!

You made the right call :D fixed!

**Comment by chrispiciullo** [comment] 2022-01-09 21:17
Thanks! You're a rockstar! ![bitmoji](https://sdk.bitmoji.com/render/panel/3fb3b537-745f-4667-a6c3-e0c397eb19ad-8cca9269-5bbe-4f28-8900-703d52e1da53-v1.png?transparent=1&palette=1&width=246)![bitmoji](https://sdk.bitmoji.com/render/panel/3fb3b537-745f-4667-a6c3-e0c397eb19ad-8cca9269-5bbe-4f28-8900-703d52e1da53-v1.png?transparent=1&palette=1&width=246)

**Comment by chrispiciullo** [comment] 2022-01-13 03:19
I'm sorry to keep re-opening this, but as we progress through our playthrough of Enigmatica 6, we're discovering things as we go. We updated to v0.5.23 to take advantage of the Shield fix, which works just fine, but It seems that the following Ars items also give the "No Recipe Found" error:

Amulet of Mana Boost
Ring of Greater Discount
Enchanter's Mirror
Belt of Unstable Gifts
Casting Wand

This was all we had the opportunity to test so far, so I'm not sure if other Ars items may have the same issue. Thanks!

**Comment by MuteTiefling** [comment] 2022-01-13 04:39
Thanks. We'll get those fixed up soon.

**Comment by MuteTiefling** [comment] 2022-01-13 16:22
@chrispiciullo Would you mind showing posting some screenshots of your recipes/setup? I'm unable to reproduce this with those items.

The issue with the shield/sword was that the recipes were not configured to ignore extra NBT on items that traditionally have it (armor, shields, weapons). None of these recipes are using any items with NBT, however. At least, they _shouldn't_ have nbt.

**Comment by YashTFEM** [comment] 2022-01-13 16:25
I had a similar problem. The problem was there were some other pedestals in range which had items in them for source automation. Just try moving your setup a bit further away from other pedestals and try to make the items again.

**Comment by Padrinony** [comment] 2022-01-13 17:29
> @chrispiciullo Would you mind showing posting some screenshots of your recipes/setup? I'm unable to reproduce this with those items.
> 
> The issue with the shield/sword was that the recipes were not configured to ignore extra NBT on items that traditionally have it (armor, shields, weapons). None of these recipes are using any items with NBT, however. At least, they _shouldn't_ have nbt.

We'll try and get those screenshots tonight.... We are friends and play on the same server.

**Comment by Padrinony** [comment] 2022-01-13 17:30
> 

We'll give this a try as we generally have them in a 5x5 orientation if I'm not mistaken.

**Comment by chrispiciullo** [comment] 2022-01-14 00:50
> 

@MuteTiefling Sorry for the delay. My pesky day job got in the way of having fun. Anyway, here are some screenshots. I took one of the little Ars setup we have without any recipes, one with the recipe for the Amulet of Mana Boost on the pedestals and a final screenshot of that recipe trying to add the reagent to the Enchanting Apparatus and the "No Recipe Found" message. I tried the recipe with both source gems (the Ars one as well as the Emendatus Enigmatica one) with the same results each time.

Let me know if you'd like more screenshots of other recipes. I'm not sure if it's worth mentioning, but there is also an error message from kubejs along with many warnings. I took the liberty of including the server log file (logs/kubejs/server.txt) here as well, on the off chance it might be related.
![ars_enchanter](https://user-images.githubusercontent.com/2933774/149432184-cc1f3181-a648-4355-b562-989fc2d6d638.png)
![amulet_mana_boost_recipe](https://user-images.githubusercontent.com/2933774/149432194-abecfccb-7eef-4a86-899b-978f7f980f02.png)
![no_item_found](https://user-images.githubusercontent.com/2933774/149432204-07814b80-1f2f-44ee-b3ec-960505a83fc9.png)
[server.txt](https://github.com/EnigmaticaModpacks/Enigmatica6/files/7866842/server.txt)

**Comment by telemenar** [comment] 2022-01-14 00:53
At a glance I think your furthest 3 Arcane Pedestals are outside of the range of the enchanter. The range is 11x11 which means 5 away in any given direction. And I think if I'm counting right yours are on the 6th block away.

**Comment by chrispiciullo** [comment] 2022-01-14 01:30
> At a glance I think your furthest 3 Arcane Pedestals are outside of the range of the enchanter. The range is 11x11 which means 5 away in any given direction. And I think if I'm counting right yours are on the 6th block away.

Well shucks, you're 100% right @telemenar. This whole time it was a PEBKAC (Problem Existed Between Keyboard And Chair)... lol I changed the pedestal layout to be tighter and it is all working just fine now. For some reason, I remember it working spread out the way we had it, but I guess not. Thanks for being our extra pair of eyes on this one!

@MuteTiefling Please feel free and close this as everything is working as intended, except for me being a big dummy. lol I appreciate all the help!

**Closed** 2022-01-14 01:33 UTC
Labels: Bug, Status: Fixed In Next Release, Status: Awaiting Information
