### ISSUE TITLE
Apiary visualiser not working properly

### ISSUE THREAD

**Issue by TheGho7t** [EnigmaticaModpacks/Enigmatica6#3659] opened 2021-11-03 23:07 UTC
### Modpack Version

6.0.5.19

### Describe your issue.

I was setting up my apiary for the first time and after I placed all of my blocks, I realized it said they were all invalid. Thought it was a bit strange.

I searched in JEI with $valid_apiary and the blocks were a jumbled, bizarre mess. I tried editing the two valid_apiary.js files but it entirely removed the search on JEI and now I'm really confused. It doesn't come back as an error or show the text in red either, it just changes nothing. This is above my Minecraft knowledge so I decided to ask here. 

I had changed them from this (The default for both):

onEvent('item.tags', (event) => {
    event.get('resourcefulbees:valid_apiary').add(validApiaryBlocks);
});

to the Default Block Tag and Default Item Tag on the RBees wiki. I switched it back to the above but I cannot replicate the search and it seems no block is allowed for my apiary now.

Any help would be much appreciated. I put the modpack version as .19 but it could be .18. I don't know where to check that on MultiMC.

Thanks.

### Have you modified the modpack?

Yes

### User Modifications

I added a couple of mods:

Ambient Sounds
Ambient World
Better weather
Pam's 2 food core, crops, trees, food extended
Creativecore

This is all I have changed.

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by theboo** [comment] 2021-11-03 23:45
So the apiary doesn't check for the block tag for validity, it now accepts any block that has collision (can't walk through basically)... The item tags are still added for JEI searchability, but also mean nothing in terms of validity...

The apiary visualiser is borked tho, it is still looking for the block tag, ignore the red... It also adds a floor which is no longer part of the apiary multiblock so ignore that as well.

Here is the issue I made in their tracker concerning the visualiser checking for the block tags still:
https://github.com/Resourceful-Bees/ResourcefulBees/issues/287

**Comment by TheGho7t** [comment] 2021-11-04 00:00
Ah, how bizarre all around. I didn't think it'd be that messed up. 

So if I make it correctly, no matter what block, I should be able to just hit create then? I saw that option was greyed out for me but I think I made it one block too large in one of the directions. I'll go check to see how that goes here shortly.

**Comment by theboo** [comment] 2021-11-04 00:09
Correct, you can still use the visualizer, just ignore both the red and the floor (it is one block too high).. also, I believe the validate button works as intended.

Lemme know if it works out

**Comment by TheGho7t** [comment] 2021-11-04 00:18
> Correct, you can still use the visualizer, just ignore both the red and the floor (it is one block too high and not part of the structure anymore anyway).. also, I believe the validate button works as intended.
> 
> Lemme know if it works out

Thank you very much for the help. I don't think I would've tried that out as I assumed it was glitched and it wouldn't work or something. 

It worked perfectly with a bunch of random blocks I threw on it.

**Comment by theboo** [comment] 2021-11-04 00:22
Sweet, glad that sorted it... I've renamed this issue and will leave it open for tracking purposes.

**Comment by TheGho7t** [comment] 2021-11-04 00:22
> Sweet, glad that sorted it... I've renamed this issue and will leave it open for tracking purposes.

Thanks again!

**Comment by theboo** [comment] 2022-01-31 20:08
Closing, was fixed awhile ago in rbees

**Closed by theboo** 2022-01-31 20:08 UTC
Labels: Status: Reported, Mod Issue
