### ISSUE TITLE
ChunkPregenerator Crashing

### ISSUE THREAD

**Issue by IainVM** [EnigmaticaModpacks/Enigmatica6#3735] opened 2021-11-16 01:58 UTC
### Modpack Version

0.5.20

### Describe your issue.

Steps that caused the issue:
 - Created TerraForge world
 - Ran command `/pregen start gen radius test SQUARE ~ ~ 50 minecraft:overworld NORMAL_GEN`

Stacktrace found in `latest.log`:
```
[01:51:21] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.crash.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:855) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?]
	at net.minecraft.server.MinecraftServer$$Lambda$38784/303714713.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.NullPointerException: No data is present for column: [-239, 81]
	at net.minecraft.world.chunk.storage.RegionSectionCache.getColumnInfo(SourceFile:634) ~[?:?]
	at net.minecraft.world.chunk.storage.RegionSectionCache.getCachedColumnInfo(SourceFile:627) ~[?:?]
	at net.minecraft.world.chunk.storage.RegionSectionCache.collectWithinChunkColumn(SourceFile:598) ~[?:?]
	at net.minecraft.village.PointOfInterestManager.collectWithinCircle(SourceFile:1117) ~[?:?]
	at net.minecraft.village.PointOfInterestManager.getAllWithinCircle(SourceFile:1097) ~[?:?]
	at net.minecraft.village.PointOfInterestManager.func_234148_d_(SourceFile:1068) ~[?:?]
	at net.minecraft.entity.ai.brain.task.WalkToHouseTask.func_212832_a_(SourceFile:53) ~[?:?]
	at net.minecraft.entity.ai.brain.task.Task.func_220378_b(SourceFile:45) ~[?:?]
	at net.minecraft.entity.ai.brain.task.MultiTask$RunType$1.func_220630_a(SourceFile:522) ~[?:?]
	at net.minecraft.entity.ai.brain.task.MultiTask.func_212831_a_(SourceFile:53) ~[?:?]
	at net.minecraft.entity.ai.brain.task.Task.func_220378_b(SourceFile:49) ~[?:?]
	at net.minecraft.entity.ai.brain.Brain.func_218218_d(SourceFile:506) ~[?:?]
	at net.minecraft.entity.ai.brain.Brain.func_218210_a(SourceFile:465) ~[?:?]
	at net.minecraft.entity.merchant.villager.VillagerEntity.func_70619_bc(VillagerEntity.java:195) ~[?:?]
	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:688) ~[?:?]
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2411) ~[?:?]
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:488) ~[?:?]
	at net.minecraft.entity.AgeableEntity.func_70636_d(SourceFile:127) ~[?:?]
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2158) ~[?:?]
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:300) ~[?:?]
	at net.minecraft.entity.merchant.villager.VillagerEntity.func_70071_h_(VillagerEntity.java:234) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?]
	at net.minecraft.world.server.ServerWorld$$Lambda$39854/2078848353.accept(Unknown Source) ~[?:?]
	at net.minecraft.world.World.func_217390_a(MixinWorldRedstone.java:554) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?]
	... 6 more
```

### Crash Report

https://pastebin.com/mMB8XaTm

### Latest Log

https://pastebin.com/heLJKG84

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by IainVM** [comment] 2021-11-16 02:00
Just to note, every time I load up this world, the pregen tries to continue and throws this exception again.

**Comment by IainVM** [comment] 2021-11-16 02:04
Also created a bug on the ChunkPregenerator tracker
https://www.curseforge.com/minecraft/mc-mods/chunkpregenerator/issues/156

**Comment by IainVM** [comment] 2021-11-16 02:50
The region mentioned in the stack trace was near where I was standing, so I deleted the pregen cache info and moved far away (outside of the region I want to pregen). Ran the command again and now I'm getting this stacktrace

```
[02:45:18] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.crash.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:855) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?]
	at net.minecraft.server.MinecraftServer$$Lambda$38795/510002824.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.NullPointerException
	at net.minecraft.world.chunk.storage.RegionSectionCache.mde13977$lambda$getWithinChunkColumn$0$0(SourceFile:592) ~[?:?]
	at net.minecraft.world.chunk.storage.RegionSectionCache$$Lambda$39882/1651830478.apply(Unknown Source) ~[?:?]
	at java.util.stream.IntPipeline$4$1.accept(IntPipeline.java:250) ~[?:1.8.0_51]
	at java.util.PrimitiveIterator$OfInt.forEachRemaining(PrimitiveIterator.java:115) ~[?:1.8.0_51]
	at java.util.Spliterators$IntIteratorSpliterator.forEachRemaining(Spliterators.java:1908) ~[?:1.8.0_51]
	at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:693) ~[?:1.8.0_51]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) ~[?:1.8.0_51]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) ~[?:1.8.0_51]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_51]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_51]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_51]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_51]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270) ~[?:1.8.0_51]
	at net.minecraft.util.math.ChunkPos$1.tryAdvance(SourceFile:168) ~[?:?]
	at java.util.Spliterator.forEachRemaining(Spliterator.java:326) ~[?:1.8.0_51]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) ~[?:1.8.0_51]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) ~[?:1.8.0_51]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_51]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_51]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_51]
	at net.minecraft.entity.passive.BeeEntity$UpdateBeehiveGoal.handler$zpd000$findNearbyHivesWithSpace(BeeEntity.java:1220) ~[?:?]
	at net.minecraft.entity.passive.BeeEntity$UpdateBeehiveGoal.func_226489_j_(BeeEntity.java) ~[?:?]
	at net.minecraft.entity.passive.BeeEntity$UpdateBeehiveGoal.func_75249_e(BeeEntity.java:1101) ~[?:?]
	at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75249_e(SourceFile:41) ~[?:?]
	at net.minecraft.entity.ai.goal.GoalSelector.startGoals(SourceFile:636) ~[?:?]
	at net.minecraft.entity.ai.goal.GoalSelector.updateGoalStates(SourceFile:573) ~[?:?]
	at net.minecraft.entity.ai.goal.GoalSelector.func_75774_a(SourceFile:555) ~[?:?]
	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:682) ~[?:?]
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2411) ~[?:?]
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:488) ~[?:?]
	at net.minecraft.entity.AgeableEntity.func_70636_d(SourceFile:127) ~[?:?]
	at net.minecraft.entity.passive.AnimalEntity.func_70636_d(AnimalEntity.java:51) ~[?:?]
	at net.minecraft.entity.passive.BeeEntity.func_70636_d(BeeEntity.java:401) ~[?:?]
	at com.resourcefulbees.resourcefulbees.entity.passive.CustomBeeEntity.func_70636_d(CustomBeeEntity.java:166) ~[?:1.16.5-0.9.9.8]
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2158) ~[?:?]
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:300) ~[?:?]
	at net.minecraft.entity.passive.BeeEntity.func_70071_h_(BeeEntity.java:218) ~[?:?]
	at com.resourcefulbees.resourcefulbees.entity.passive.ResourcefulBee.func_70071_h_(ResourcefulBee.java:122) ~[?:1.16.5-0.9.9.8]
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?]
	at net.minecraft.world.server.ServerWorld$$Lambda$39850/235804421.accept(Unknown Source) ~[?:?]
	at net.minecraft.world.World.func_217390_a(MixinWorldRedstone.java:554) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?]
	... 6 more
```

Crash Report: https://pastebin.com/3mecVNp5
Latest Log: https://pastebin.com/naN9s8aY

**Comment by Speiger** [comment] 2021-11-16 16:30
Ok I read through the code. And I have to say this is weird because the "crashing" code does not exist.

The function that crashes is this:
```java
at net.minecraft.world.chunk.storage.RegionSectionCache.mde13977$lambda$getWithinChunkColumn$0$0(SourceFile:592) ~[?:?]
```
But this function does not exist. Neither with Forge mappings (the ones I have don't have a name for that function) or Mojang mappings. Also the class the function is called from is half the size of what the error says...

And the function Minecraft does call works like a charm. Just to show the function that Vanilla actually calls.
```java
   protected Optional<R> getOrLoad(long p_219113_1_) {
      SectionPos sectionpos = SectionPos.of(p_219113_1_);
      if (this.outsideStoredRange(sectionpos)) {
         return Optional.empty();
      } else {
         Optional<R> optional = this.get(p_219113_1_);
         if (optional != null) {
            return optional;
         } else {
            this.readColumn(sectionpos.chunk());
            optional = this.get(p_219113_1_);
            if (optional == null) {
               throw (IllegalStateException)Util.pauseInIde(new IllegalStateException());
            } else {
               return optional;
            }
         }
      }
   }
```
This function NEVER EVER returns null or throw a NullPointException.
readColumn is also so written that it if it can not find the file it will create a empty PointOfInterestData, because that is a real case scenario.

Ok what does chunkpregen actually do with POIs.

Basically ChunkPregen is saving Pois if they get to large and the forcefully unload them.
Why? Because they are a memory leak. They never unload on their own.
If you don't do that you can not have a large in minecraft anymore. The hardcap of the world would be: 16k x 16k to 32k x 32k (Blocks)
After that you would run out of memory if you had 7-8GB free of ram when the world was first created.
Maybe even less. Its a long time since I tested the hardcap.

But ChunkPregen always saves first before removing the reference only, after the Game already has finished its update logic. The IOWorker still has the data and if it is requested then it will load it up as needed from the IOWorker or from the SaveFile itself. Otherwise if it fails to do so it will create a empty one.
So there is a no crash scenario.

And since the code being called does not even exist with Vanilla Mappings, yet the Bee function does exist does mean it is code that was added by another mod and ChunkPregen is still until 1.18 completely asm/mixin free

So this is a incompatibly caused by a third party. Until it's proven otherwise I will treat it as not Chunkpregens bug.
For the sole reason: First time happening after 1 year of working without any problems. And Vanilla AI was working fine with that.

**Comment by Darkere** [comment] 2021-11-16 16:39
The crash you were looking at was presumably caused by deleting the pregen cache. I'm not sure what exactly that does, but I could imagine that causing problems.

The original crash mentions mixins from roadrunner. 
```
java.lang.NullPointerException: No data is present for column: [-239, 81]
	at net.minecraft.world.chunk.storage.RegionSectionCache.getColumnInfo(SourceFile:634) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:roadrunner.mixins.json:ai.poi.fast_retrieval.SerializingRegionBasedStorageMixin,pl:mixin:A}```
So that is likely the reason for the non existant code. Maybe @MaxNeedsSnacks could take a look when he has time.

**Comment by MaxNeedsSnacks** [comment] 2021-11-16 16:44
See https://github.com/MaxNeedsSnacks/roadrunner/issues/21; since neither of the original posters have replied whether this works for them though, please try and see whether the prerelease (available on GH) fixes this, I'll do another full release then

**Comment by Speiger** [comment] 2021-11-16 16:47
@Darkere eh nope Since i remove the "reference" it will trigger a reload from the IOWorker and as @MaxNeedsSnacks already pointed out this is most likely a crash from a different mod.

Also please stop using "but you do stuff and that's causing the issue" argument when i clearly stated this worked fine for 1 year without issues so someone else is the cause... That's just lazy.

**Comment by Speiger** [comment] 2021-11-16 17:06
@MaxNeedsSnacks yeah this "should" fix it. Though we kinda have a collision of interest with our mods that we kinda need to sort out... This is just the "obvious crash" collision, but not the "bigger bug" that we do add if you fix this "crash" right now...

**Comment by IainVM** [comment] 2021-11-16 17:22
@MaxNeedsSnacks Sadly with your build artifact I've hit the `NullPointerException`. So might have fixed the POI issue, but now I'm back to the original StackTrace.

```
[17:16:15] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.crash.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:855) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?]
	at net.minecraft.server.MinecraftServer$$Lambda$38780/788668991.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.NullPointerException: No data is present for column: [-239, -77]
	at net.minecraft.world.chunk.storage.RegionSectionCache.getColumnInfo(SourceFile:637) ~[?:?]
	at net.minecraft.world.chunk.storage.RegionSectionCache.getCachedColumnInfo(SourceFile:630) ~[?:?]
	at net.minecraft.world.chunk.storage.RegionSectionCache.getWithinChunkColumn(SourceFile:584) ~[?:?]
	at net.minecraft.village.PointOfInterestManager.func_219137_a(SourceFile:1039) ~[?:?]
	at net.minecraft.village.PointOfInterestManager.func_226350_a_(SourceFile:71) ~[?:?]
	at net.minecraft.village.PointOfInterestManager$$Lambda$39850/958551535.apply(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267) ~[?:1.8.0_51]
	at net.minecraft.util.math.ChunkPos$1.tryAdvance(SourceFile:168) ~[?:?]
	at java.util.Spliterator.forEachRemaining(Spliterator.java:326) ~[?:1.8.0_51]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) ~[?:1.8.0_51]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) ~[?:1.8.0_51]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_51]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_51]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_51]
	at net.minecraft.entity.passive.BeeEntity$UpdateBeehiveGoal.handler$zpd000$findNearbyHivesWithSpace(BeeEntity.java:1220) ~[?:?]
	at net.minecraft.entity.passive.BeeEntity$UpdateBeehiveGoal.func_226489_j_(BeeEntity.java) ~[?:?]
	at net.minecraft.entity.passive.BeeEntity$UpdateBeehiveGoal.func_75249_e(BeeEntity.java:1101) ~[?:?]
	at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75249_e(SourceFile:41) ~[?:?]
	at net.minecraft.entity.ai.goal.GoalSelector.startGoals(SourceFile:636) ~[?:?]
	at net.minecraft.entity.ai.goal.GoalSelector.updateGoalStates(SourceFile:573) ~[?:?]
	at net.minecraft.entity.ai.goal.GoalSelector.func_75774_a(SourceFile:555) ~[?:?]
	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:682) ~[?:?]
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2411) ~[?:?]
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:488) ~[?:?]
	at net.minecraft.entity.AgeableEntity.func_70636_d(SourceFile:127) ~[?:?]
	at net.minecraft.entity.passive.AnimalEntity.func_70636_d(AnimalEntity.java:51) ~[?:?]
	at net.minecraft.entity.passive.BeeEntity.func_70636_d(BeeEntity.java:401) ~[?:?]
	at com.resourcefulbees.resourcefulbees.entity.passive.CustomBeeEntity.func_70636_d(CustomBeeEntity.java:166) ~[?:1.16.5-0.9.9.8]
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2158) ~[?:?]
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:300) ~[?:?]
	at net.minecraft.entity.passive.BeeEntity.func_70071_h_(BeeEntity.java:218) ~[?:?]
	at com.resourcefulbees.resourcefulbees.entity.passive.ResourcefulBee.func_70071_h_(ResourcefulBee.java:122) ~[?:1.16.5-0.9.9.8]
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?]
	at net.minecraft.world.server.ServerWorld$$Lambda$39829/593661180.accept(Unknown Source) ~[?:?]
	at net.minecraft.world.World.func_217390_a(MixinWorldRedstone.java:554) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?]
	... 6 more
```

This Exceptions did arise after I removed the pregen cache, I removed the pregen cache to stop the pregen from automatically continuing and hitting this Exception over and over.

Crash Report: https://pastebin.com/8xM9aJxN
Latest Log: https://pastebin.com/5BBNzS7J

**Comment by Speiger** [comment] 2021-11-16 17:23
@IainVM the Pregen cache is just the "TaskCache" and the "Memory" of what the pregenerator was doing. Deleting it does NOTHING to the pregeneration itself...

**Comment by Speiger** [comment] 2021-11-16 17:29
To temp fix this: Remove the Roadrunner mod temporarily during Pregeneration. After that is done install the Roadrunner mod back in and just don't run any pregeneration with it. That will fix your issue. 

Until @MaxNeedsSnacks, maybe even jellysquid3 and I have solved that problem...
Because this will also be a Fabric Problem if ChunkPregen decides to move to fabric at any point.

**Comment by IainVM** [comment] 2021-11-16 17:30
@Speiger Yeah, was just confirming that since @Darkere wondered if deleting the cache caused a problem. So was just clarifying that I deleted the cache to stop the task itself. Since there's no way to stop/pause a pregen task before getting back into a world (to my knowledge).

I'll try your suggestion to temp disabling of Roadrunner and see if that bypasses the issue.

**Comment by Speiger** [comment] 2021-11-16 17:31
@IainVM there is a config with "autorestart" that you can set to false that would stop a task from starting if you join a world.

**Comment by IainVM** [comment] 2021-11-16 17:32
> @IainVM there is a config with "autorestart" that you can set to false that would stop a task from starting if you join a world.

Ahh perfect, thanks. I feel bad that I didn't even check for a config. I just yeet'd the cache. :') The 3am "hit it with a hammer" solution at the time.

**Comment by Speiger** [comment] 2021-11-16 17:34
@MaxNeedsSnacks also this issue comes because I replace the "Long2ObjectMap" when a pregeneration starts...
I can fix this and not replace it if Lithium is detected that would fix the entire issue but that would require a small code change on your part because there is a reason i do that.

**Comment by IainVM** [comment] 2021-11-16 18:15
Pregen went longer than it had been, but decided to do a move focused pregen, so `/pregen stop test`
And got a Exception mentioning the `Long2ObjectMap` this might be out of scope of this bug report, though thought since you're chatting about the `Long2ObjectMap` then worth saying here.

```
[18:09:53] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.crash.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:855) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?]
	at net.minecraft.server.MinecraftServer$$Lambda$38782/1553537625.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
	at it.unimi.dsi.fastutil.longs.Long2ObjectLinkedOpenHashMap.moveIndexToLast(Long2ObjectLinkedOpenHashMap.java:497) ~[fastutil-8.2.1.jar:?]
	at it.unimi.dsi.fastutil.longs.Long2ObjectLinkedOpenHashMap.getAndMoveToLast(Long2ObjectLinkedOpenHashMap.java:572) ~[fastutil-8.2.1.jar:?]
	at pregenerator.common.utils.collections.Long2ObjectCustomMap.get(Long2ObjectCustomMap.java:25) ~[?:V1.16-3.2.0]
	at net.minecraft.world.chunk.storage.RegionSectionCache.func_219106_c(SourceFile:67) ~[?:?]
	at net.minecraft.world.chunk.storage.RegionSectionCache.func_219113_d(SourceFile:75) ~[?:?]
	at net.minecraft.village.PointOfInterestManager.func_219149_a_(SourceFile:87) ~[?:?]
	at net.minecraft.village.PointOfInterestManager$$Lambda$39884/715049533.apply(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_51]
	at java.util.stream.IntPipeline$4$1.accept(IntPipeline.java:250) ~[?:1.8.0_51]
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110) ~[?:1.8.0_51]
	at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:693) ~[?:1.8.0_51]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) ~[?:1.8.0_51]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) ~[?:1.8.0_51]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_51]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_51]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_51]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_51]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270) ~[?:1.8.0_51]
	at net.minecraft.util.math.ChunkPos$1.tryAdvance(SourceFile:168) ~[?:?]
	at java.util.Spliterator.forEachRemaining(Spliterator.java:326) ~[?:1.8.0_51]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) ~[?:1.8.0_51]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) ~[?:1.8.0_51]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_51]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_51]
	at java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:479) ~[?:1.8.0_51]
	at java.util.stream.ReferencePipeline.min(ReferencePipeline.java:520) ~[?:1.8.0_51]
	at net.minecraft.village.PointOfInterestManager.func_234148_d_(SourceFile:110) ~[?:?]
	at net.minecraft.entity.ai.brain.task.WalkToHouseTask.func_212832_a_(SourceFile:53) ~[?:?]
	at net.minecraft.entity.ai.brain.task.Task.func_220378_b(SourceFile:45) ~[?:?]
	at net.minecraft.entity.ai.brain.task.MultiTask$RunType$1.func_220633_a(SourceFile:96) ~[?:?]
	at net.minecraft.entity.ai.brain.task.MultiTask$RunType$1$$Lambda$40115/1189703810.test(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174) ~[?:1.8.0_51]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_51]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_51]
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1351) ~[?:1.8.0_51]
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126) ~[?:1.8.0_51]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:529) ~[?:1.8.0_51]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:516) ~[?:1.8.0_51]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) ~[?:1.8.0_51]
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152) ~[?:1.8.0_51]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_51]
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464) ~[?:1.8.0_51]
	at net.minecraft.entity.ai.brain.task.MultiTask$RunType$1.func_220630_a(SourceFile:97) ~[?:?]
	at net.minecraft.entity.ai.brain.task.MultiTask.func_212831_a_(SourceFile:53) ~[?:?]
	at net.minecraft.entity.ai.brain.task.Task.func_220378_b(SourceFile:49) ~[?:?]
	at net.minecraft.entity.ai.brain.Brain.func_218218_d(SourceFile:506) ~[?:?]
	at net.minecraft.entity.ai.brain.Brain.func_218210_a(SourceFile:465) ~[?:?]
	at net.minecraft.entity.merchant.villager.VillagerEntity.func_70619_bc(VillagerEntity.java:195) ~[?:?]
	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:688) ~[?:?]
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2411) ~[?:?]
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:488) ~[?:?]
	at net.minecraft.entity.AgeableEntity.func_70636_d(SourceFile:127) ~[?:?]
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2158) ~[?:?]
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:300) ~[?:?]
	at net.minecraft.entity.merchant.villager.VillagerEntity.func_70071_h_(VillagerEntity.java:234) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?]
	at net.minecraft.world.server.ServerWorld$$Lambda$39833/1032488667.accept(Unknown Source) ~[?:?]
	at net.minecraft.world.World.func_217390_a(MixinWorldRedstone.java:554) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?]
	... 6 more
```

Crash Report: https://pastebin.com/pzB8vMpm
Latest Log: https://pastebin.com/kDJBgcUN

**Comment by Speiger** [comment] 2021-11-16 18:38
This looks like a Multithreading issue...
Where 2 threads trying to access the same thing.
Never ran into that crash before to be honest. But the fix to this would be synchronizing it... Only 1 thread can access it at the same time.

**Comment by Speiger** [comment] 2021-11-17 04:53
Small Update on status for @NillerMedDild.

I am going to make a patch next weekend that should be released fairly quickly.
It will address the issue and I will just hope that Lithium will patch its side quickly too.
If not worst case: Pregen will fight vanilla for keeping stuff loaded that shouldn't but that isn't to much of a issue.
It will also fix lithiums Memory leak that comes with mc during pregeneration.

**Comment by NillerMedDild** [comment] 2021-11-17 10:04
Excellent, thank you :)

**Comment by IainVM** [comment] 2021-11-17 14:52
Also to note the work around of disabling Roadrunner has worked well and haven't had any of these issues anymore, just eventual slowdowns because of increasing memory usage.

**Comment by Speiger** [comment] 2021-11-28 05:50
@NillerMedDild this is not fixed completely because @MaxNeedsSnacks still hasn't really implemented his side of the fix...

**Comment by Speiger** [comment] 2021-12-14 07:10
@NillerMedDild ok a release was issued and it seems this is now fixed completly from what i noticed (Havent tested the new version though. But the fixes they implemented "should" address the issues)

**Closed** 2022-01-06 12:15 UTC
Labels: Status: Fixed In Next Release, Mod Issue
