### ISSUE TITLE
Every time I get poisoned my world essentially breaks and crashes trying to load

### ISSUE THREAD

**Issue by Spadfinn** [EnigmaticaModpacks/Enigmatica6#5312] opened 2023-01-18 01:17 UTC
### Modpack Version

Enigmatica 6 - E6 - 1.16.5 Enigmatica 6 1.6.2

### Describe your issue.

Every time I get poisoned, my world breaks and I can't load into it. Sometimes it breaks the entire pack and I can't even open it. It has happened twice now, both times immediately after being poisoned. 

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NielsPilgaard** [comment] 2023-01-18 07:30
Thanks for the report. Please provide your latest.log and if possible your debug.log too

**Comment by Spadfinn** [comment] 2023-01-18 20:27
I hope at least some of these are helpful
[debug-1.log.gz](https://github.com/EnigmaticaModpacks/Enigmatica6/files/10450565/debug-1.log.gz)
[latest.log](https://github.com/EnigmaticaModpacks/Enigmatica6/files/10450567/latest.log)
[debug-2.log.gz](https://github.com/EnigmaticaModpacks/Enigmatica6/files/10450568/debug-2.log.gz)
[debug-3.log.gz](https://github.com/EnigmaticaModpacks/Enigmatica6/files/10450569/debug-3.log.gz)
[debug-4.log.gz](https://github.com/EnigmaticaModpacks/Enigmatica6/files/10450570/debug-4.log.gz)
[Uploading debug-5.log.gz…]()

**Comment by Darkere** [comment] 2023-01-18 22:03
Duplicate of #5304

**Closed by Darkere** 2023-01-18 22:03 UTC
Labels: Bug, Status: Awaiting Information
