### ISSUE TITLE
PCBEE Honeycomb Centrifuging

### ISSUE THREAD

**Issue by Kevin-Marsh** [EnigmaticaModpacks/Enigmatica6#4267] opened 2022-02-20 11:30 UTC
### Modpack Version

Dev

### Describe your issue.

The Pcbee honeycomb cannot be processed in a centrifuge without a honey bottle. Other honeycombs dump their fluid into the centrifuges fluid output which can be pulled out into a tank. I believe this doesn't work in the PCBee's case since the fluid and the circuit board are reversed. This has the potential to jam up the centrifuge if you aren't using bottles. IIs it possible to switch those around so it can be processed like the others?

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by TemperedFool** [comment] 2022-02-20 11:39
This is a duplicate of #4168. This design is unfortunately intentional, due to limitations of the centrifuge recipes.

**Closed** 2022-02-20 11:39 UTC
Labels: Duplicate

**Comment by MuteTiefling** [comment] 2022-02-20 12:00
Oop, my bad

**Comment by TemperedFool** [comment] 2022-02-20 12:02
Is all good; we'd just have to change what it produces which I'd rather not. And tbh, it's not really a huge inconvenience to either run a second centrifuge or otherwise automate bottles, having done it a few times both ways.

**Comment by Kevin-Marsh** [comment] 2022-02-20 12:07
Would it be possible to add an acid bottle recipe?

**Comment by TemperedFool** [comment] 2022-02-20 14:42
Probably, but given how easy working around this is, and the fact that other bees (again, see Ender Bee) require the same, I don't think it's worth the work.

**Comment by ApionXD** [comment] 2022-03-25 23:36
@TemperedFool I apologize for bringing this back up
This is my current setup: 
![image](https://user-images.githubusercontent.com/5356562/160214754-b07a4573-7d63-4a59-900d-d26bcbf2f3eb.png)
Why isnt this working? There is no fluid in the output tank.

**Comment by TemperedFool** [comment] 2022-03-25 23:39
Take out both the combs and bottles; put the bottles back in first.
