### ISSUE TITLE
Draconic Evolution

### ISSUE THREAD

**Issue by NickyMB** [EnigmaticaModpacks/Enigmatica6#5260] opened 2022-11-15 10:02 UTC
### URL

https://www.curseforge.com/minecraft/mc-mods/draconic-evolution/files

### Why would you like the mod added?

Mod add a lot of powerful items which are liked by many Minecraft players

**Comment by Kanzaji** [comment] 2022-11-15 10:13
Duplicate of #3521and #3049

**Closed** 2022-11-15 10:14 UTC
Labels: Suggestion
