### ISSUE TITLE
recipe conflict

### ISSUE THREAD

**Issue by Damalas75** [EnigmaticaModpacks/Enigmatica6#3950] opened 2021-12-25 23:45 UTC
### Describe your suggestion

Chisel and Iron knife recipe conflict suggestion Polymorph mod

### Why would you like this added/changed?

It solves the issue of recipe conflicts by adding a slide bar to select which item to craft making both recipes accessible

**Comment by MuteTiefling** [comment] 2021-12-26 01:46
We already have polymorph ;D it's just a little broken in the current release.

Still, this should be a simple conflict to resolve.

**Comment by Ridanisaurus** [comment] 2021-12-26 08:21
Duplicate of #3948

**Closed** 2022-01-05 10:46 UTC
Labels: Duplicate
