### ISSUE TITLE
Dupe Bug with Compacting Drawers

### ISSUE THREAD

**Issue by Rixhephtos** [EnigmaticaModpacks/Enigmatica6#4191] opened 2022-02-05 00:00 UTC
### Modpack Version

v0.5.25

### Describe your issue.

Hello, a player on a server I staff reported a duping bug and was able to recreate it for me.

He placed a diamond in the Compacting Drawer, then took it out. He placed 64 Slate blocks in the compacting drawer, and the drawer showed Slate on top, Diamonds on the bottom left, and Copper Nuggets, of all things, on the bottom right. He was then able to withdraw multiple diamonds. I was unable to do it myself but I watched him do it and saw the drawer with 3 different items displayed on it, and watched him withdraw diamonds from a drawer that he just put slate into.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by Rodg88** [comment] 2022-02-05 05:01
Can't reproduce, any more details?

**Comment by Oreo735** [comment] 2022-02-05 16:16
It works here's what I did:
1. Put one copper ingot in the compacting drawer.
2. Remove the ingot from the drawer.
3. Put one diamond in the drawer.
4. Remove the diamond.
5. Put 64 Slate in the drawer.
6. Pull the 64 Slate.
7. Put the 64 Slate AGAIN.
8. Pull 64 diamonds.

**Comment by Oreo735** [comment] 2022-02-05 16:25
In addition try putting and pulling 64 Slate multiple times until the diamond shows on left corner. 
It also works on anything compactible not just diamonds.

**Comment by Rodg88** [comment] 2022-02-05 19:03
![image](https://user-images.githubusercontent.com/2611674/152655004-0d236431-939b-4eec-881f-33dcdd939246.png)

Yep got it to work.

**Comment by Rixhephtos** [comment] 2022-02-06 00:36
Oreo735 is the player I mentioned. Thanks for the clarification, Oreo :)

**Comment by DavidAGullo** [comment] 2022-06-11 17:57
This bug was fixed in 1.3.0

**Closed** 2022-06-11 18:22 UTC
Labels: Status: Fixed In Next Release, Mod Issue
