### ISSUE TITLE
Ars Nouveau crashing game

### ISSUE THREAD

**Issue by phoenixborn635** [EnigmaticaModpacks/Enigmatica6#5331] opened 2023-02-12 12:54 UTC
### Modpack Version

1.6.2

### Describe your issue.

The lightning glyph, when amplified and combined with the aethermancy robes from ars elemental, will crash the game when used on the floor?

### Crash Report

https://gist.github.com/phoenixborn635/82792ca80cf094a48f447ceaaab1052b

### Latest Log

https://gist.github.com/phoenixborn635/7611edfda61f599535bb01b2fee77361

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

Off Brand Anime God#0755

**Comment by NielsPilgaard** [comment] 2023-02-12 17:26
Huh, seems odd - @MuteTiefling have you seen this before?

**Comment by Darkere** [comment] 2023-02-12 17:35
Duplicate of #5304

**Closed by Darkere** 2023-02-12 17:35 UTC
Labels: Bug
