### ISSUE TITLE
Potion of Spell Damage II uncraftable

### ISSUE THREAD

**Issue by g0urra** [EnigmaticaModpacks/Enigmatica6#5152] opened 2022-08-06 18:32 UTC
### Modpack Version

1.4.1

### Describe your issue.

Attempting to craft Potion of Spell Damage II (Nether Wart > Magebloom > Glowstone Dust) in a Brewing Stand instead crafts Calming Potion (10:00). That potion is instead crafted using Nether Wart > Resourceful Honey Bottle > Glowstone Dust according to JEI.
![bild](https://user-images.githubusercontent.com/12349921/183261599-1c507cf0-5f89-4b0a-8f5b-3ca55813f9b2.png)
![bild](https://user-images.githubusercontent.com/12349921/183261607-bd8ce75e-2a55-4d2f-9281-383c1f5e82e9.png)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

g0urra#1690

**Comment by NielsPilgaard** [comment] 2022-08-07 11:32
Duplicate of #4719

**Comment by g0urra** [comment] 2022-08-07 13:54
> Duplicate of #4719

Which is closed as a duplicate as another issue, that was a duplicate of another issue, which was closed without a resolution.
Seems like just a circle of unresolved issues.

**Comment by NielsPilgaard** [comment] 2022-08-08 06:19
Woops 😅 reopened, I doubt we'll ever find the cause of this though, tbh.

**Closed** 2023-02-15 19:26 UTC
Labels: Bug, Status: Won't Fix
