### ISSUE TITLE
Market crash

### ISSUE THREAD

**Issue by SammyWhamy** [EnigmaticaModpacks/Enigmatica6#4392] opened 2022-03-12 18:55 UTC
### Modpack Version

Enigmatica 6 Expert 1.0.0

### Describe your issue.

When I put an emerald (right clicking, if it matters) into the Market (trading thing) without having a trade selected, my game completely crashed.

### Crash Report

https://gist.github.com/SammyWhamy/878fee5f8027abcb8b805fffe675ecf5

### Latest Log

https://gist.githubusercontent.com/SammyWhamy/d8182ba2bd5e28c9eee08fd87511c9a5/raw/89db188a811caf32cb02919fa4e411a5088b36d7/e6e-1.0.0-latest.log

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment] 2022-03-12 19:21
Thanks for the report - This is fixed in the mod, but hasn't been released yet: https://github.com/ModdingForBlockheads/FarmingForBlockheads/issues/127

**Comment by NillerMedDild** [comment] 2022-03-12 19:21
Oh, duplicate of https://github.com/EnigmaticaModpacks/Enigmatica6/issues/3803 btw

**Closed by NillerMedDild** 2022-03-12 19:21 UTC
Labels: Duplicate
