### ISSUE TITLE
Centrifugal separator Honey Bottle produces CoFH Core Honey

### ISSUE THREAD

**Issue by Jmad12** [EnigmaticaModpacks/Enigmatica6#5225] opened 2022-10-08 12:50 UTC
### Modpack Version

1.4.1

### Describe your issue.

Most everything produces Resourceful bees Honey. This includes every recipe in the Resourceful Bees Centrifuges, as well as when putting a Honey Block through a Magma Crucible.
![image](https://user-images.githubusercontent.com/14036772/194708321-17e64920-8087-4d9b-b724-456ccf3f62ca.png)
But when you put a honey bottle through a Centrifugal Separator, it produces CoFH Core Honey
![image](https://user-images.githubusercontent.com/14036772/194708345-16f5197c-932a-455a-ab34-bca6f57ac6ae.png)
It's only (JEI) uses are honeyed apples (seems unintended since it doesn't show up when looking up honeyed apple) and rebottling. Maybe also burning it on a beecon (untested)
![image](https://user-images.githubusercontent.com/14036772/194708419-e06be88b-60e1-4861-9b11-da1114756ca3.png)

May be linked to #5211

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

Rex#1543

**Comment by NielsPilgaard** [comment] 2022-10-08 19:03
Thanks for the thorough report, but it is a duplicate of the issue you linked I'm afraid.

**Closed by NielsPilgaard** 2022-10-08 19:03 UTC
Labels: Duplicate
