### ISSUE TITLE
Game Crash in Beepedia

### ISSUE THREAD

**Issue by jiru6552** [EnigmaticaModpacks/Enigmatica6#4211] opened 2022-02-08 01:04 UTC
### Modpack Version

0.5.25

### Describe your issue.

Game crashes to launcher when selecting Water Bee in the beepedia. Sometimes when it doesn't crash right away, it will crash when I select the breeding tab on the Water Bee.

### Crash Report

https://gist.github.com/jiru6552/4e1e47dc72ed5d9ca16c02e1b9e65a81

### Latest Log

https://gist.github.com/jiru6552/ef9ab029aae50c120feabfb89918e51b

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by TemperedFool** [comment] 2022-02-08 03:25
This is actually a dupe of #4076 that I've forgotten to resolve. I'll push a fix later this week.

**Closed** 2022-02-08 03:25 UTC
Labels: Bug, Duplicate
