### ISSUE TITLE
Redstone Pen's redstone tracks behave unexpectedly 

### ISSUE THREAD

**Issue by Iris-xii** [EnigmaticaModpacks/Enigmatica6#4126] opened 2022-01-24 16:37 UTC
### Modpack Version

Enigmatica 6 0.5.25+ (develop branch)

### Describe your issue.

Redstone Pen's redstone tracks behave unexpectedly, becoming unpowered under certain circumstances even though normally they would be powered.

To replicate: 
Create a setup like this:
![image](https://user-images.githubusercontent.com/48930896/150824293-75cd16b3-ca45-46f3-9f9b-f1111fa4178a.png)
![image](https://user-images.githubusercontent.com/48930896/150824315-6b7e9c97-d0c3-47bf-a868-db331c969fe7.png)

It consists of a on lever, a line of redstone going up the side of a block, but with the top face clear, and another line going down on the other side.

Then simply add a new track of redstone to the top face using a single click.
![image](https://user-images.githubusercontent.com/48930896/150824533-ee5ed3dd-051f-45df-9291-2ec2f89c00f8.png)
This will be the result. The top track is powered but the track on the other side doesn't get powered.
Breaking and replacing some of the lines can get it to behave as expected. (which is why the new line must be applied using a single click)

![image](https://user-images.githubusercontent.com/48930896/150824665-79d9c06e-59f2-429f-afe8-3f88338df876.png)

Redstone also has trouble traveling through corners, but that might be intended.
![image](https://user-images.githubusercontent.com/48930896/150824805-bf22e651-2da4-4f3a-a2c8-1f834b23068d.png)

Please note that this is only the simplest way to replicate these issues I've found. The setup seems rather forced, but it happens naturally in a semi-consistent way for example on this mess of an altar automation:
![image](https://user-images.githubusercontent.com/48930896/150824921-7a917a0a-a2af-4e31-b9fe-9caf7a4f7033.png)

### Crash Report

N/A

### Latest Log

N/A

### Have you modified the modpack?

Yes

### User Modifications

Removed PackMenu and Tips, disabled mosquito spawns. 

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by Rodg88** [comment] 2022-01-24 16:42
To supplement, this video shows some of the weird behavior, particularly at the end of the video. Adding the top half of the vertical track actually disabled the redstone signal:
https://user-images.githubusercontent.com/2611674/150825449-9a63212c-b9a9-496b-84db-60b7084c9a95.mp4

**Comment by stfwi** [comment] 2022-01-26 15:55
Hi all, (and ty Rodg for the forward in the mod repository). 
I quickly risked a glimpse, 
- The first shown situation is definitely unexpected and very likely a bug in my mod.
- The second, where the connector-to-connector does not transfer signals, is intended. That allows to power a block from multiple sides, and easily making an `OR` logic that way. For transferring RS through a block, the Relays are RS sensitive on their bottom side.

Let me double check in the mod what's messy there and come back with a fix or questions ;) Cheers,-

**Comment by stfwi** [comment] 2022-01-28 18:24
Alright, I could reproduce and (most likely) fix the problem, for E6 the fix version would be `redstonepen-1.16.5-1.0.7`, for E7+ the corresponding versions are also in approval.

**Closed** 2022-02-25 20:53 UTC
Labels: Status: Fixed In Next Release, Mod Issue
