### ISSUE TITLE
RFTools Builder loses infusion and inventory when broken with pickaxe

### ISSUE THREAD

**Issue by Jyrath** [EnigmaticaModpacks/Enigmatica6#4620] opened 2022-04-11 00:31 UTC
### Modpack Version

1.1.2 expert

### Describe your issue.

When breaking a RFTools Builder with a pickaxe, the Builder loses all infusion, and the inventory of Shape Card and Filter is deleted.

Shift+Right Clicking with a RFToolsBase Smart Wrench preserves inventory and infusion. However, this is inconvenient, and has not been how the builder has worked in the past.

https://user-images.githubusercontent.com/54685113/162646611-9e63db78-c199-4fd0-bf79-1a6b0893481b.mp4

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment] 2022-04-11 04:42
Duplicate of #4568

**Closed by NillerMedDild** 2022-04-11 04:42 UTC
Labels: Bug
