### ISSUE TITLE
Coke oven crash to desktop (expert)

### ISSUE THREAD

**Issue by Toonlink264** [EnigmaticaModpacks/Enigmatica6#4025] opened 2022-01-09 09:57 UTC
### Modpack Version

Dev branch

### Describe your issue.

i make the coke oven and smacked it with the hammer (as you're supposed to do) and it crashed me to desktop. unpon reloading the pack and reopening the world it was completed and i could break and reform with no issue

### Crash Report

https://paste.ee/p/ojnjj

### Latest Log

https://paste.ee/p/FEKzi

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment] 2022-01-09 18:42
Duplicate of #4013 sorta :)

**Closed by NillerMedDild** 2022-01-09 18:42 UTC
Labels: Bug
