### ISSUE TITLE
Lava block near PCR refinery turns into obsidian instantly under certain very specific conditions

### ISSUE THREAD

**Issue by Iris-xii** [EnigmaticaModpacks/Enigmatica6#3853] opened 2021-12-05 21:32 UTC
### Modpack Version

Enigmatica 6 0.5.21+ (commit  299be9dd4697a36ac3b0d03e7fcae0cf2cef11df dev branch, expert mode)

### Describe your issue.

A lava block near a PCR refinery may turn into obsidian with no noticeable temperature gain. It can be replicated by:

- Placing down a refinery controller and 4 tanks on top. Insulate all sides with blocks except one.
- Pipe oil into the refinery
- Place down a magma block on the side of the refinery.
- Wait until heat stabilizes at 99º
- Break the block, then place down some lava instead. Then it will turn into obsidian instantly, with no noticeable temperature gain in the refinery. 

There's a chance this might not work, trying to quickly replace the magma block with obsidian usually works though. Under some circumstances it happens every single time, but I'm unsure how to replicate that.

### Crash Report

N/A

### Latest Log

N/A

### Have you modified the modpack?

Yes

### User Modifications

Disabled Alex's mobs crimson mosquito spawns through config, removed Tips and PackMenu

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment] 2021-12-06 09:22
Thank you for the report, I will investigate the issue.

**Comment by YashTFEM** [comment] 2021-12-06 10:12
> Thank you for the report, I will investigate the issue.

I'm that's actually a feature of PNC

**Comment by NillerMedDild** [comment] 2021-12-06 10:17
Ah right 😄 this is indeed a feature

**Comment by telemenar** [comment] 2021-12-06 23:47
The report isn't that things turn to obsidian at all which is the expected behavior. (Place down lava heat is transferred to refinery exhausting the heat capacity of the block block transitions to the exhausted state - obsidian in the case of lava.)

The report is that they seem to do so instantly without transferring any heat, which seems strange.

**Comment by TemperedFool** [comment] 2021-12-06 23:49
Yeah, tbh as reported this doesn't seem like intended behavior.

**Comment by MuteTiefling** [comment] 2022-01-08 03:25
I've been unable to reproduce this one. Assuming it's been fixed in PNC.

**Closed by MuteTiefling** 2022-01-08 03:25 UTC
Labels: Bug
